### ISSUE TITLE
Graphic Design Resources

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/MUDDLE#18]
Hello MUDDLERS! 

Winter is here so let us bring in our toys, cozy up with our machines, and MUDDLE the cold months away! I've pulled together some GitHub originating Graphic Design Resources I thought you all might like. Let me know which are your favorites and please share all that you create! :snowflake::snowman::snowflake:

[primitive](https://github.com/fogleman/primitive)
By @fogleman
A command line operated (unless you've got a Mac!) primitive shape generator that transforms traditional works of art into modern masterpieces. The demonstration alone is worth popping over to this repo!  :red_circle::large_orange_diamond:

[Geometrize](https://github.com/Tw1ddle/geometrize)
By @Tw1ddle
A downloadable primitive shape generator (for those still hesitant at the command line but who still want in on the fun :) Again, the demonstration is reason enough to go check it out! :small_blue_diamond::large_blue_circle:

[MyPaint](https://github.com/mypaint/mypaint)
By @mypaint
A no mess, no fuss painting app for artists. Features include an infinite canvas, full screen mode, tablet support, and configurable brushes. :art:

[Oblivion](https://github.com/jweinst1/Oblivion)
By @jweinst1
Want to design graphics at the command line? Try this SVG producing programming language. Not for the faint of heart, but the results could be amazing! :stars:

[LyricsPoster](https://github.com/samuelmeuli/lyrics-poster)
By @samuelmeuli
This free web app lets you create posters of your favorite artists composed from their lyrics! Could be a fun gift for anyone thinking about (or dreading) the season of gift-giving. :gift:

**Comment by RJP43** [comment]
As you explore new tools don't forget to capture your process.  💻 📹
  
For those wanting to know more about screen recording, here is a promising resource I am exploring.
Development existing on the OBS Project GitHub (attributed to @DDRBoxman @jp9000 @notr1ch)  [OBS Studio](https://github.com/obsproject/obs-studio) is a free and open source software for live streaming and screen recording - see more info and download here: https://obsproject.com/.
