### ISSUE TITLE
Praise and gratitude!

### ISSUE THREAD

**Issue by nadinejl** [taylorcate/MUDDLE#23]
I'm not sure where to put this but I just want to send some love and gratitude for the wonderful work of @taylorcate and @RJP43! I dug around in the MUDDLE Wiki this morning and found such lovely things! Rebecca's "[Why Muddle](https://github.com/publishing-bitbytebit/MUDDLE/wiki/Why-MUDDLE%3F)" article positively gave me the connection tingles the deeper I went, including but not limited to the quotes which she beautifully attributed to Taylor! So many blooming things in there. Also the [Techtual Condition](https://github.com/publishing-bitbytebit/MUDDLE/wiki/Our-%22Techtual%22-Condition) by Taylor, so clear, compassionate and courageous... I love it all. 

I also saw in [MUDDLE workflows](https://github.com/publishing-bitbytebit/MUDDLE/wiki/THE-MUDDLE-WORKFLOW) (and previously, heard via email from Taylor just before that) that MUDDLing direct via Github is coming soon and I'm excited! (Although, Taylor's inspiring vision of multiple humanities command-lining have me looking brightly up another tall mountain of possibility!) Anyway, thanks for all of this, and sending love your way for continued wonders to blossom here in this loamy sand. ❤️🎉

**Comment by taylorcate** [comment]
@nadinejl 
You have no idea how much your kind words bolster us :revolving_hearts: This is the perfect place to have any and all MUDDLE related conversations so thank you so much for dropping this here! I apologize if I didn't tag you correctly in my Instagram post :sweat: I just got so excited when I saw you opened this Issue I'm afraid I jumped too quickly to share it! 

As soon as the MUDDLING on GitHub tutorial is written up, we'll alert you here and link to the new page on the MUDDLE workflows page. So excited for all that's to come!!

Best, Tay

**Comment by nadinejl** [comment]
@taylorcate Please don’t be sorry for that; it didn’t bother me at all! I loved the post! I don’t know what the heck I’m doing on Instagram most of the time! 🙈🙊 Thanks once again for your wonderfully kind encouragement and let’s MUDDLE on!  🐵🐒💖  :) :) :)  



On 26 Jan 2019, at 15:53, taylorcate <notifications@github.com> wrote:

@nadinejl
You have no idea how much your kind words bolster us 💞 This is the perfect place to have any and all MUDDLE related conversations so thank you so much for dropping this here! I apologize if I didn't tag you correctly in my Instagram post 😓 I just got so excited when I saw you opened this Issue I'm afraid I jumped too quickly to share it!

As soon as the MUDDLING on GitHub tutorial is written up, we'll alert you here and link to the new page on the MUDDLE workflows page. So excited for all that's to come!!

Best, Tay
