### ISSUE TITLE
🐖 Making Lifelong Messes - An Invitation

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/MUDDLE#32]
## Dearest Friends and MUDDLErs, 

MUDDLE's management has been on a break these past few weeks and I wanted to pop on here to give some sort of explanation. I realized quickly that the reason is more complicated than "we've been busy" or "we've been focusing on other things" and so I hope you'll bear with me as I attempt to write something a little more honest. 

For those of you who don't know, MUDDLE's Technical Editor, @RJP43, and I just graduated with our Master's degrees in Textual Studies and Digital Humanities. Anyone you ask will define Digital Humanities differently—just check out Jason Heppler's [What is Digital Humanities?](https://whatisdigitalhumanities.com/) if you don't believe me—and this variability and indeterminancy follows those that study DH wherever they go. For me DH has become a lifelong pursuit of process. Whether it be art, music, composition, daily life, or human existence more generally, I want to know how you do it because I'm interested in what makes us tick. Like a child tracing cracks in the sidewalk with chalk, I use the tools at hand to reveal our human tendency to make mistakes. (If you visit this comment's revision history you'll see exactly what I mean.) :point_up:

I realized that I want to know others' processes because I'm trying to find tools to decipher myself—to understand my motivations and transform my actions into steps forward instead of backward. Most of our social media spaces and virtual communities "thrive" on touch ups and false realities, and this internet infatuation with impossible standards is overwhelming and unhelpful. Through GitHub, we've created a community that breeds positivity and fallibility in equal measure, and we thank every one of you for your bravery and commitment to this project. We set out to make a magazine and discovered a whole new way of thinking. :milky_way:

Occupied with this new-wav[y]e thinking, we forgot to make a magazine. :cold_sweat: _(always making messes, always learning)_ We thought we might do something a bit clever instead but that's not totally unlike what we originally had in mind...did you follow that? 
 
### With your help, we want to collect and share our community's best interactions on our [MUDDLE Issues Board](https://github.com/publishing-bitbytebit/MUDDLE/issues) for the "official" first Issue of MUDDLE Mag. :clap: If you could, please, send us via Insta, Twitter, or GitHub up to :keycap_ten: MUDDLE interactions/artworks/processes you'd like us to feature in the first Issue. The deadline is June 30th and the Issue will arrive in time for Independence Day! :fireworks:

Be sure to check out [@muddle_mag](https://www.instagram.com/muddle_mag/) on Insta for examples of what we're looking for. :eye: Please let me know if you run into any trouble or if you have any questions! Always here and happy to help. 

:heartpulse:

Sincerely, Tay

_**When we live we make big messes. It's unavoidable, and we need to show others that they aren't alone in the mud.**_

**Comment by gkthiruvathukal** [comment]
Here's to making a beautiful mess!
Congratulations on completing the MA DH, @taylorcate and @RJP43!
Peace

**Comment by taylorcate** [comment]
### Tagging everyone for pings :wave:

@publishing-bitbytebit/founding-members @gmoe @nadinejl @gkthiruvathukal @jcoyne47 @backpacker396 @jksily @tymonaghan @dislocate @zmstell

**Comment by nadinejl** [comment]
Ooooh love this, speaks to my heart. This is the kind of creative muddle I always seem to be in! I mean ALWAYS! Even at this very moment. :))) Huge congrats for your Masters' degrees @taylorcate and @RJP43 — massive achievement! especially with such wonderful missions! — and excitement for the magazine. Will have a root through my sandboxes and mud puddles and see what shoots out begging to bloom.
