### ISSUE TITLE
Let's Workshop! - Introducing November's NEWEST MUDDLErs

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/MUDDLE#8]
@RJP43 
![A fridge note describing where a MUDDLER might workshop their work with the editor. Quoted text: "Sorry! I couldn't help but play with your toys while you were away and I had some questions about your process... Meet me in: The Mudroom or Your Backyard" This note, specifically, directs the MUDDLER to the Mud Room](https://raw.githubusercontent.com/taylorcate/MUDDLE/master/PromotionalMaterials/InHouse/FridgeNotes/EditorsNote_MeetMeIn_BACKYARD.png)

**Comment by taylorcate** [comment]
@nadinejl

Thank you so much for forking us! I want to introduce you to MUDDLE's Technical Editor, Rebecca @RJP43. She will be your number one resource for understanding how to navigate the repo and how to get MUDDLING. I'm linking our previous conversation for her here. 

Best, Tay

https://github.com/nadinejl/nadinejl.github.io/issues/1

**Comment by nadinejl** [comment]
@taylorcate @RJP43 

Thank you so much for inviting me to fork you! So far it's been exciting, though I've no idea what I'm doing! @Wnuke is a big help in the tech department. I posted something to something this morning in a very muddling way, and I think I'm now supposed to make a pull request! That's what @Wnuke told me before we left for school this morning anyhow. I'm going to work on it now.

**Comment by taylorcate** [comment]
@nadinejl

If you run into any snares just let us know! Also, thank you so much for your wonderful comment on our YouTube video 💓 and for following us on Instagram! We can't wait to see your latest MUDDLE 😊

**Comment by RJP43** [comment]
@nadinejl Welcome to the MUDDLE_mag backyard and ¡huzzah! you are well on your way to muddling! The first step was forking. CL{ON][OPY}ING is such fun when you make it your own. We see your personal version of the MUDDLE backyard - [https://github.com/nadinejl/MUDDLE]( https://github.com/nadinejl/MUDDLE) ♻️ Perhaps @wnuke will fork too; many backyards make a neigh[B]{2}oard. The muddle sandbox is all about creation and process. At the forefront of c{reat][aptur}ing collaborative art and c{aptur][reat}ing the process of said art - in [m]any iterations - building a community is vital. Head into the settings of your forked MUDDLE and add an issues, wiki, and projects board[s] so MUDDLE][edito}rs in the community can directly reach out to you with qu][sugg}estions personally workshoping your muddle in your own backyard; in turn, keeping this upstream neighborhood backyard available for larger community d{evelopment][iscussion}s. While you are in your fork's settings, check to be sure your notifications are set to be notified of any activity on your fork. As others learn how muddling goes, We][They might need to reach out to learn more of your process[es]. ¡ALL in growing the neigh{BBoard][borhood! The yolk of [y]our work will need to be created collaboratively - from start to end - so as you move your work from your personal devices into your personally cloned online sandbox and neighBBboard, @taylorcate and I will need special collaborative access to help in case there are any big bugs along the way. In settings, you will see an option to add collaborators - go ahead and add us both, please. ONCE we see your invitation to collaborate, we can customize the discussion of process and production in your backyard. Not only does this allow a more focused workshopping space for each individual creator these steps also act as our safety net in keeping the upstream not "too muddled" for new neighbors. ALSO this ensures your "process to production" is fully documented singularly and it will be up to us Editors in moving the b{y][i}t[e]s during production to the mag's community process record as it becomes necessary to represent the processes of those accepted in the Spring. ¡?See you in your backyard, soon!¿ 💜♻️✌🏼

**Comment by nadinejl** [comment]
@RJP43 @taylorcate 👏👏 Thank you so much! This was just what I needed! I have added you both as collaborators. This all sounds great! Thrilled about it all! 💚✨💛✨💙👍🙏👌Do I add @wnuke as collaborator as well?

**Comment by nadinejl** [comment]
p.s. I love the fridge note graphic. 😀

**Comment by RJP43** [comment]
@nadinejl as an important part of your little community it would make sense to have @wnuke join in on the collaboration. Expect a note in your backyard soon! 😉 Veryyyyy excited to work with you!

**Comment by taylorcate** [comment]
@snblickhan

Thank you so much for forking us! We're looking forward to MUDDLING with you. Before you can start, however, there are a few things we'll need to set up so you can get the most out of your playtime experience. Our Technical Editor, @RJP43 Rebecca, can assist you in this set up. For now, let me direct you to the [MUDDLE Wiki](https://github.com/taylorcate/MUDDLE/wiki) page which has a brief description of the project and a breakdown of the workflow. Thanks again and MUDDLE on!

Best, Tay

**Comment by taylorcate** [comment]
@jksily

Thank you for submitting your first MUDDLE! We are so looking forward to future collaboration. I want to formally introduce you to MUDDLE's Technical Editor, @RJP43 Rebecca, who will be your primary source of aid for all things tech. She will walk you through setting up your own Issues and Projects boards so that your contributions to the MUDDLE community can take shape and we can comment as they grow. Thanks again and MUDDLE on!

Best, Tay

**Comment by taylorcate** [comment]
@gkthiruvathukal

Thank you for submitting your first MUDDLE! We are looking forward to future collaboration. Our wonderful Technical Editor, @RJP43 Rebecca (as you know of course) will walk you through setting up your own Issues and Projects boards so that your contributions to the MUDDLE community can take shape and we can comment on them as they grow. Thanks again and MUDDLE on!

Best, Tay

**Comment by nadinejl** [comment]
Ah! So happy I finally found this thread again! Had been poking around the Github alleyways, trying to find it; a lost newbie lamb... or pony... neigh! In the end I found it via email. :) And now I see all upstream convos can be found by bookmarking "https://github.com/taylorcate/MUDDLE/issues," is that right❓🧐🤩
 
I would love to have some of your above helpful posts tacked up in my own "backyard," while I play in the sandbox... is there some way for me to copy them over there? I have done some weird things in my yard and I'm in a right muddle. Don't know how to fix. 🤓Happy to learn it and work on it, in my slow and spiralling way... 🌀√🙆‍♀️ᛘ 🆗  #helpfordummies #please :)

**Comment by taylorcate** [comment]
@nadinejl

You are doing fine! More than fine! Just be patient with yourself and it will all come together. 

If you go into your forked MUDDLE repo settings, you'll see an option to add an "Issues" and "Projects" board. Once you add those to your forked repo we will be able to stage conversation threads, like the one above, over in YOUR backyard. Then, once we can talk in your "Issues" thread, @RJP43 and I can identify where you're at with your MUDDLE and can help you get it pushed into the main MUDDLE repo. 

Please let me know if you have any questions! 💓

**Comment by nadinejl** [comment]
@taylorcate 
Done! Very kind help, thanks very much.  :)

**Comment by RJP43** [comment]
@gkthiruvathukal @jksily @backpacker396 :tada:Huzzah!:tada: Congratulations on successfully forking and contributing to the sandbox via a pull request. While you are a few leap|commit}s ahead of some neighbors who are just getting started we'd like to see ALL OUR NEIGHBORS (@nadinejl and @snblickhan, too) [customize you|thei}r forks](https://github.com/taylorcate/MUDDLE/blob/master/HouseStyles/ForkingFun.md)!  Please note that while I am still working on this documentation there is plenty process populated already that will hopefully assist each of you in muddling onward!
